language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
    email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("XGBoost")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
